### ISSUE TITLE
PuntoMedio

### ISSUE THREAD

**Issue by JenniferGarciaDeLaCalle** [JenniferGarciaDeLaCalle/SpaiEcp2JenniferGarcia#2]
[Información detallada](https://github.com/JenniferGarciaDeLaCalle/SpaiEcp2JenniferGarcia/wiki/Obtener-punto-medio-en-la-clase-Point)

**Comment by AngelaSSanchez** [comment]
Estoy haciendo el método del punto medio, pero no pasa las pruebas porque al hacer la división de las coordenadas entre 2, uno de los resultados sale como double (1.5). Tendría que cambiar la declaración de las variables 'x' e 'y' de int a double, o dividir siempre por números pares. ¿Cómo procedo?

**Comment by JenniferGarciaDeLaCalle** [comment]
Como has indicado modifica las variables 'x' e 'y' de int a double, para que el calculo sea correcto.

**Comment by AngelaSSanchez** [comment]
Acabo de ver que es mucho más fácil, en vez de cambiar la definición de las variables, en el assertEquals de las pruebas hay que añadir un tercer parámetro con el error permitido. ¿Lo añado yo a la clase de prueba PointTest, sigo con el cambio anterior, o cambias la prueba y hago un Fetch cuando lo tengas?

**Comment by JenniferGarciaDeLaCalle** [comment]
Si no me equivoco eso ya está añadido a los assertEquals de testPuntoMedio(), el tercer parámetro es necesario si los valores que vas a comparar no son enteros. Pero en este caso sigues necesitando guardar el 1.5 y el int no te va a dejar.

**Comment by AngelaSSanchez** [comment]
Ya está todo corregido
