### ISSUE TITLE
SegundoApellido

### ISSUE THREAD

**Issue by JenniferGarciaDeLaCalle** [JenniferGarciaDeLaCalle/SpaiEcp2JenniferGarcia#3]
[Información detallada](https://github.com/JenniferGarciaDeLaCalle/SpaiEcp2JenniferGarcia/wiki/A%C3%B1adir-el-registro-de-segundo-apellido-en-la-clase-User)

**Comment by ghost** [comment]
Hola Jennifer,

He incluido los cambios de este ticket. Sin embargo, los test no pasan correctamente. Resulta que en la clase UserTest, métodos testFullName y testGetName (líneas 18 y 33 respetivamente) el assert espera el resultado "Juan Antonio" en ambos casos.

Pienso que aquí se encuentra el error, dado que el método format (que se llama en el constructor al principio) convierte únicamente el primer caracter del string a mayúscula, dejando el resto a minúscula. En este caso, creo que al test le chirría la inicial 'A' de "Antonio" en el string anterior.

Te dejo que le eches un vistazo y me comentas. En cuanto solucionemos este detalle, pruebo, mergeo con develop y cierro el ticket.

Saludos

**Comment by JenniferGarciaDeLaCalle** [comment]
El método testFullName() es validador tanto de este ticket como del ticket 'NombresCompuestos' es normal que te falle, dado que para que funcione necesitas tener ambos ticket implementados.
El otro método testGetName() es validador únicamente del ticket 'NombresCompuestos' así que también es normal que falle.
Cuando ambos tickets estén implementados el test debería funcionar sin ningún problema.

Un saludo.

**Comment by ghost** [comment]
Tienes toda la razón, ni me había parado a mirar los otros dos tickets la verdad. Ya está completa esta tarea y mergeada en develop. Cierro ticket.

Saludos
