### ISSUE TITLE
DecimalMenor

### ISSUE THREAD

**Issue by JenniferGarciaDeLaCalle** [JenniferGarciaDeLaCalle/SpaiEcp2JenniferGarcia#5]
[Información detallada](https://github.com/JenniferGarciaDeLaCalle/SpaiEcp2JenniferGarcia/wiki/Decimal-m%C3%A1s-peque%C3%B1o-en-la-clase-DecimalCollection)

**Comment by MiriamSP** [comment]
Implementado método 'mediaLista()' 
Listo para corrección!

**Comment by JenniferGarciaDeLaCalle** [comment]
Si no me equivoco has implementado el método decimalMenor(), que es el de este ticket, no el mediaLista().
Pasa el test DecimalCollectionTest, y el método testDecimalMenor() que es el que se encarga de evaluar este ticket debería funcionar sin problemas. Si no falla y es correcto une la develop a tu rama, si no hay conflictos une tu rama a la develop, y cierra este ticket.

Un saludo.

**Comment by MiriamSP** [comment]
Hola Jennifer, 
Implemente ambos métodos (mediaLista y decimalMenor) en la misma Feature.01, 

Ambos corresponden a la clase DecimalCollection.

Ya han pasado los test unitarios, y actualice la rama Feature.01. 
Pero al fusionar con develop me dio error de conflicto (ya estaba el metodo).

Perdona el lio...

Un saludo

Miriam

**Comment by MiriamSP** [comment]
Hola Jennifer, 

como estaba un poco lioso, he decidio empezar de nuevo con las 2 mejoras de la clase DecimalCollection.
Como no estaban fusionadas con develop, la feature 01 inicial se puede desechar.

Entonces te resumo como quedaría:
- decimalMenor – Feature11
- mediaLista - Feature12

Ambas han pasado los test y he subido ambas ramas a tu repositorio.

Y he terminado de fusionar ambas ramas con tu rama develop.

Me dices si esta correcto, para cerrar este ticket y el otro relacionado.

Miriam

**Comment by MiriamSP** [comment]
Por cierto, Travis te da un error:
Could not find .travis.yml, using standard configuration.

he visto en tu repositorio que te falta el fichero .travis.yml.

cuidado con el . inicial, que es necesario (te lo comento porque a mi me da el mismo problema por esto)
un saludo

Miriam

**Comment by JenniferGarciaDeLaCalle** [comment]
Lo del .travis ya lo sabía, pero gracias de todas formas.

Hay varios errores con tus ramas.
El primer problema es que generaste una rama desde el primer commit, y yo después de eso hice varios commit para modificar la develop. También existe la posibilidad de que te lo descargaste a local antes de que yo hiciese esas modificaciones. El problema de esto está en que el .gitignore de los test, a ti te sale, cuando yo en uno de esos commit lo elimine, por lo que tu código no ha podido pasar las pruebas dado que tus ramas no tienen esos test.
La segunda cosa que veo es que no has unido tus ramas a la rama develop, como me has indicado, pero gracias a esto podemos hacer lo siguiente:
Te propongo la solución que creo que es más rápida.
1. Cópiate los métodos que has creado en un fichero separado.
2. Borrar tus ramas actuales (todas)
3. Comienza una nueva rama desde la rama develop actual.
4. Añade en esta rama los métodos que creaste
5. Pasa los test, súbelo, une la develop a tu rama, y si no da conflicto (que no debería), une tu rama a la develop.

Existe otra opción que es unir la develop a tu rama y resolver los conflictos, pero te saldrían muchos, ya que elimine bastantes cosas que no hacían falta para el proyecto.

Espero que con los pasos anteriores te resulte fácil, si tienes alguna duda coméntamelo.

**Comment by JenniferGarciaDeLaCalle** [comment]
Miriam al resolver los conflictos has tocado mucho código que no era tuyo sino de tus compañeros y eso no lo debes hacer dado que ahora yo no sé si ese es el correcto o no. Por favor cópiate los métodos que has creado para cada clase fuera del proyecto, y no toques nada del servidor.
Cuando te los hayas copiado avísame.
A continuación, yo restaurare un commit anterior y te lo diré, para que puedas a partir de ese crear las ramas que necesites para tus modificaciones.

**Comment by MiriamSP** [comment]
Hola Jennifer,

Creo que no he tocado código, salvo los métodos que me has indicado a modificar. Pero por favor, si estoy equivocada, indícame que parte para tenerlo en cuenta para futuras prácticas, aprender y no volver a cometer estos errores.

He empezado desde cero tal como indicabas, me he vuelto a importar tu pryto. he creado una rama nueva (20). 
Y aquí he subido las modificaciones de las clase DecimalCollection: métodos mediaLista y decimalMenor.
He pasado los test.
Y he fusionado esta rama con la develop.

Parece que ya esta correcto. Cuando me confirmes que es así me pongo con el de la clase Fraction.

gracias

Un saludo

Miriam

**Comment by JenniferGarciaDeLaCalle** [comment]
Miriam te comento lo que haces mal y como solucionarlo, porque te ha vuelto a pasar lo mismo que antes.
Cuando te descargues un proyecto de github, la única rama que te aparece inicialmente creada es la rama master. Lo primero que hay que hacer es descargarse la rama develop en local. Y a partir de esta rama develop es donde tú creas tu nueva rama, trabajas sobre ella, y por último unes tu rama a la develop.
Ahora mismo he borrado todas tus ramas en el servidor, te comento que tienes que hacer, para realizar lo anterior:
1. Haz un pull del proyecto. (Veras que tus ramas 20, 13, 12 y 11, ya no existen).
2. Sobre el proyecto descargado, click derecho ->Team -> Show in repository view.
3. En esta nueva ventana hay una carpeta con el proyecto, si despliegas Branch, te aparecerán dos carpetas:
   Local
   Remote Tracking -> abre esta carpeta. Te aparecerán todas las ramas que existen en el servidor. Haz click sobre la rama 'origin/develop' y click en 'Checkout as new local branch'. Con esto  te estas creando una copia de la rama develop en local. Si te fijas en la carpeta Local, ahora además de la rama master te aparecerá la rama develop.
4. Sitúate en la rama develop, aparecerá marcada con un tick. Click derecho, 'Create Branch', y creas tu propia rama, con el nombre que quieras.
5. Realizas las modificaciones sobre esta rama. (Debajo te he copiado los métodos que habías creado).
6. Pasas los test.
7. Realizas commit.
8. Fusión de develop con tu rama. Como estas situada sobre tu rama (aparecerá con un tick) y click derecho, en la rama develop, 'Merge'. Con esto te traes todas las modificaciones de la develop a tu rama. En este punto te podrían salir conflictos, si existen te solucionarían ahora.
9. Por último la fusión con la develop es otra cosa en la que fallas, es lo mismo que antes pero desde la rama develop. Tienes que situarte en la rama develop (aparecerá con un tick) y click derecho, en la rama que creaste en el paso 4, 'Merge'. En el historial de ramas te aparecerá el siguiente mensaje 'Merge branch 'Nombre de tu rama creada' into develop'.

Y con esto estarían todos los cambios realizados. Espero haberte aclarado algo, si tienes alguna duda pregúntame sin problemas.
Un saludo.

Tu código, perteneciente a las ramas que he borrado:

```
public Fraction multiplicarFraccion(Fraction f) {
    Fraction fResultado = new Fraction();
    fResultado.numerator = this.numerator*f.numerator;
    fResultado.denominator = this.denominator* f.denominator;
    return fResultado;
}


public double decimalMenor(){
    double lower = Double.POSITIVE_INFINITY;
    for (double item : this.collection) {
        if (item < lower) {
            lower = item;
        }
    }
    return lower;
}    

public double mediaLista(){
    double suma = 0;
    for (double item : this.collection) {
        suma += item;
    }
    return suma / this.size();
}
```

**Comment by MiriamSP** [comment]
Hola Jennifer,
Gracias por el detalle de la explicación, antes de seguir, para intentar hacerlo bien, te pongo en que punto estoy y la duda.
(hasta entonces todos los puntos seguidos tal como indicabas sin problema):

![pytojennifer](https://cloud.githubusercontent.com/assets/14840898/10316054/e99a485a-6c5d-11e5-85db-34c7eb2ee411.jpg)

Ya he hecho las clases, test, y commit en la clase DecimalCollection. Y ya he fusionado mi feature40 con la rama develop (copia de la tuya remota: origin/develop).
Todo Ok hasta aquí (sin conflictos).
Ahora en el punto 9, entiendo que debería de fusionar esta develop (local mia) con la tuya remota. ES así?

Un saludo

Miriam

**Comment by JenniferGarciaDeLaCalle** [comment]
No, el paso 9, es otra cosa, el que tú me indicas sería el 10, que se ha olvidado ponértelo.

En el punto 8, no fusionas tu rama feature40 con la rama develop. El punto 8, copia el contenido de tu rama develop local, en tu rama feature40. Esto se hace por si un compañero hubiese modificado algo que te afecte a ti.

La diferencia con el punto 9, es que en este caso te copias el contenido de tu rama feature40 en la rama develop (local), de tal forma que las modificaciones realizadas en tu rama, se incorporarían a la develop. Si te das cuenta a diferencia con el de antes, es que ahora el tick está en la develop, como me muestras en la imagen y haces click derecho sobre la feature40, 'Merge'. En el punto 8, era al revés.

Para finalizar a la lista de antes le falta un paso:
10. Fusionar con la develop (remota). Para ello haces click derecho sobre tu develop (local), 'Push Branch...'. 

Espero habértelo aclarado.

Saludos.

**Comment by MiriamSP** [comment]
Hola Jennifer,

He seguido los pasos:
- Ya tengo el punto 8 realizado, Fusión Feature40 con develop local --> Sin Conflictos.
  - 9: Fusión develop local con Feature40, Ya tengo los cambios en mi develop local.

10 - Fusion develop local con remota

Por favor, comprueba si está correcto!

gracias!

**Comment by JenniferGarciaDeLaCalle** [comment]
Esta perfecto! Genial
Ya puedes cerrar este asunto.

Ahora para la modificación de la otra clase realiza los mismos pasos (desde el punto 4, ya que los puntos anteriores ya los tienes hechos).

Un saludo.

**Comment by MiriamSP** [comment]
Genial!!!

muchas gracias por todo!
