### ISSUE TITLE
MediaLista

### ISSUE THREAD

**Issue by JenniferGarciaDeLaCalle** [JenniferGarciaDeLaCalle/SpaiEcp2JenniferGarcia#6]
[Información detallada](https://github.com/JenniferGarciaDeLaCalle/SpaiEcp2JenniferGarcia/wiki/Media-de-una-lista-en-la-clase-DecimalCollection)

**Comment by MiriamSP** [comment]
Método ya implementado, testeado,  y subido junto a DecimalMenor!
