### ISSUE TITLE
MitadFraccion

### ISSUE THREAD

**Issue by JenniferGarciaDeLaCalle** [JenniferGarciaDeLaCalle/SpaiEcp2JenniferGarcia#8]
[Información detallada](https://github.com/JenniferGarciaDeLaCalle/SpaiEcp2JenniferGarcia/wiki/Mitad-de-una-fracci%C3%B3n-en-la-clase-Fraction)

**Comment by ghost** [comment]
Tarea completada.

Comentar que en la clase de test aparecía como valores esperados 20 y 8 para el numerador y denominador respectivamente, cuando la fracción inicial es 10/2. Es verdad que 20/8 es la mitad que 10/2, pero me pareció un poco raro ya que para llegar a ese resultado primero multiplicas la fracción por 2 y luego la divides entre 4 (o viceversa), cuando hay opciones más naturales como dividir el numerador entre 2 (lo que hice yo), multiplicar el denominador por 2, etc.

Como para poder pasar el test con éxito debía hacer lo anterior de multiplicar por 2 y dividir por 4 (que me parece raro como digo) me he tomado la libertad de modificar el test (dijo Jesús en clase que podían hacerlo los programadores) poniendo el assert a la fracción inicial (10/2) dividida entre 2. Además, de este modo la prueba vale para cualquier valor de numerador y denominador, siempre y cuando la fracción dé la mitad claro.

Ya me comentas qué te parece el cambio del test. Aún no cierro el ticket por si acaso.

Saludos

**Comment by JenniferGarciaDeLaCalle** [comment]
Tienes razón me confundí al ponerlo.
Pero la solución final que has realizado no sirve para todos los casos, piensa que al dividir el numerador entre 2, en este caso te funciona porque es par (10), pero si fuese impar fallaría, ya que no te va a dejar asignar un double en un int, esto funcionaria si cambiases las declaraciones de int a double, pero es más lioso.
El caso más sencillo, que no fallaría, es el otro que propones, el de multiplicar el denominador por 2. En ese caso no tendrías el problema anteriormente mencionado.
Un saludo.

**Comment by ghost** [comment]
Hola,

Es verdad, no había contemplado ese caso, escogí la solución de dividir el numerador al azar y no lo tuve en cuenta. He subido ya eso corregido (multiplicando el denominador x2) y fusionado con develop. Creé también un test probando con un número impar y funciona ok.

Creo que con esto ya está todo, cierro ticket.

Saludos
