### ISSUE TITLE
MultiplicarFraccion

### ISSUE THREAD

**Issue by JenniferGarciaDeLaCalle** [JenniferGarciaDeLaCalle/SpaiEcp2JenniferGarcia#9]
[Información detallada](https://github.com/JenniferGarciaDeLaCalle/SpaiEcp2JenniferGarcia/wiki/Multiplicar-fracciones-en-la-clase-Fraction)

**Comment by MiriamSP** [comment]
Realizado: Método MultiplicarFraccion:Devuelve una fracción resultado de la multiplicación de la fracción actual por una recibida como parámetro. 

Feature13 y fusionado con develop.

Las pruebas pasaron satisfactoriamente.

No te he subido el fichero de Test porque tenía error (DIRTY_WORKTREE), para solucionarlo tuve que borrar tu fichero y crear uno de Test para este método.

Te lo pongo aquí por si te sirve para hacer las pruebas:

@Test
    public void TestmultiplicarFraccion(){
        Fraction f = new Fraction(5, 2);
        assertEquals(5, f.getNumerator());
        assertEquals(2, f.getDenominator());
        Fraction f2 = new Fraction(10, 2);
        Fraction fREsultado;
        fREsultado = f2.multiplicarFraccion(f);
        assertEquals(50, fREsultado.getNumerator());
        assertEquals(4, fREsultado.getDenominator());
    }

Espero a que me indiques para cerrar el ticket.

un saludo.

Miriam

**Comment by MiriamSP** [comment]
Hola Jennifer,

En las pruebas me ha entrado una duda sobre este método.

El resultado tiene que ser la propia fracción multiplicada por una que recibe como parámetro.

O se devuelve una fracción independiente, resultado de la multiplicación de ambas...

Espero haberme explicado.

un saludo

Miriam

**Comment by JenniferGarciaDeLaCalle** [comment]
No tienes que devolver nada. Sino que asignas el resultado a las variables numerador y denominador de la propia clase. Si te fijas en la clase 'FractionTest' se lanza el metodo 'multiplicarFraccion()' y para comprobar el resultado, se obtiene los valores del numerador y denominador de la clase 'Fraction'.

**Comment by MiriamSP** [comment]
Hola,

Efectivamente al ver el test me dí cuenta de que lo había interpretado incorrectamente, ya ha le vuelto a implementar, y el test fue Ok.

Ya he subido el cambio, espero que esta vez haya ido bien a la primera!

un saludo

Miriam

**Comment by JenniferGarciaDeLaCalle** [comment]
Esta perfecto!
Te cierro el ticket.
